
name: Build

on: [push, pull_request]

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run:   |
              sudo apt-get install build-essential git make cmake autoconf automake libpng-dev
        shell: bash
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run CAKE
        run: dotnet run --project ./build/Build.csproj
      - name: Package artifacts
        uses: actions/upload-artifact@main
        with:
          name: FreeType-${{ matrix.os }}
          path: |
            artifacts/*
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    needs: [ build ]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download artifacts for Windows x64
        uses: actions/download-artifact@v3
        with:
          name: FreeType-windows-latest
          path: artifacts-windows-x64
      - name: Download artifacts for macOS
        uses: actions/download-artifact@v3
        with:
          name: FreeType-macos-latest
          path: artifacts-macos
      - name: Download artifacts for Linux x64
        uses: actions/download-artifact@v3
        with:
          name: FreeType-ubuntu-22.04
          path: artifacts-linux-x64
      - name: Run CAKE
        run: dotnet run --project ./build/Build.csproj -- "--target=Package"
      - name: Push packages
        run: dotnet nuget push src/bin/Release/*.nupkg --source https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Make a release
        uses: ncipollo/release-action@v1
        with:
          name: 'MonoGame.Library.FreeType ${{ github.ref_name }}'
          tag: ${{ github.ref_name }}
          allowUpdates: true
          removeArtifacts: true
          artifacts: "bin/Release/*.nupkg"
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_type == 'tag'

